name: Validate Flake Formatting

on:
  workflow_dispatch:
  push:
    paths:
      - "**.nix"

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix run nixpkgs#alejandra -- -c .
